# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-gl-api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore
      working-directory: gl-api
    - name: Build
      run: dotnet build --no-restore
      working-directory: gl-api
    - name: Restore test
      run: dotnet restore
      working-directory: gl-apiTests
    - name: Build test
      run: dotnet build --no-restore
      working-directory: gl-apiTests
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: gl-apiTests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-gl-api # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

