name: push-feature-branch

on:
  push:
    branches: [ "*", "!main" ]

jobs:
  build-test-runcodecoverage:
    uses: ./.github/workflows/build-test-codecov.yml

  push-image:
    needs: build-test-runcodecoverage
    env:
      IMAGE: davebosleyhpe/glapi
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
     # These are prerequisites for the docker build step
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and publish container image with tag
      uses: docker/build-push-action@v4
      with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
                        ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}      
